title: <p align="center"> Chris Tran </p>

logo: "/profile pic?raw=true"

description:
  <p align="center">
  #<a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mansoor-k-5687b1299/">LinkedIn</a> |
  <a href="https://github.com/123-mansoor">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
